[package]
name        = "{{project-name}}"
description = "{{description}}"
version       = "0.1.0"
edition       = "2021"
rust-version  = "1.75"
license       = "MIT OR Apache-2.0"

[dependencies]
tpt-async = { version = "0.1", features = ["macros", "io"] }

[profile.release]
opt-level = 3
lto = true
